name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build docker image
      run: |
        docker build -t noobcoder007/docker-graphql:0.0.2 .
        docker build -t noobcoder007/docker-graphql:latest .
    - name: Push docker image
      run: |
        docker push noobcoder007/docker-graphql:0.0.2
        docker push noobcoder007/docker-graphql:latest .
